/** Declaration file generated by dts-gen */

export function clear(key: string): void;

export function clearGlobal(key: string): void;

export function get<T>(key: string): T;

export function getValueStackCopy(): Object;

export function pop(): void;

export function push(values: Object): void;

export function pushArgv(): void;

export function pushEnv(): void;

export function pushJsonFile(filePath: string): void;

export function set<T>(key: string, value: T): void;

export function setGlobal<T>(key: string, value: T): void;

export function toObject(): Object;

export namespace clear {
    const prototype: {
    };

}

export namespace clearGlobal {
    const prototype: {
    };

}

export namespace get {
    const prototype: {
    };

}

export namespace getValueStackCopy {
    const prototype: {
    };

}

export namespace pop {
    const prototype: {
    };

}

export namespace push {
    const prototype: {
    };

}

export namespace pushArgv {
    const prototype: {
    };

}

export namespace pushEnv {
    const prototype: {
    };

}

export namespace pushJsonFile {
    const prototype: {
    };

}

export namespace set {
    const prototype: {
    };

}

export namespace setGlobal {
    const prototype: {
    };

}

export namespace toObject {
    const prototype: {
    };

}

